name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/myapp


            git pull origin main


            cd TodoAI_React/TodoAI_React
            docker build -t todoai-fe .


            cd /root/myapp/TodoAI
            docker build -t todoai-api .

            # 🔥 Restart containers
            docker stop todoai-fe todoai-api || true
            docker rm todoai-fe todoai-api || true

            docker run -d -p 80:80 --name todoai-fe todoai-fe
            docker run -d -p 5000:5000 --name todoai-api todoai-api
